Fix compilation for cmxs
ygrek/ocaml-mysql pull request #10
Opened 2017-06-09 08:29 UTC by Zzull

2017-06-18 05:47 UTC, ygrek requested changes

2017-06-18 05:47 UTC, ygrek commented on Makefile.in
> +opt: native-code-library mysql.cmxs
afaik `ocamllopt -shared` is not available everywhere, so need to do a configure check and enable this target conditionally

2017-06-26 07:06 UTC, merged

2017-06-26 07:07 UTC, ygrek commented
Thanks!
I tweaked it a little bit in master, please check

2017-06-26 08:19 UTC, Zzull commented
Looks good to me. You made it way more robust, thanks